title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request
        Suggest an improvement or new capability for AIP.
  - type: textarea
    id: problem
    attributes:
      label: Problem / Use Case
      description: What problem does this solve? What's the use case?
      placeholder: "As an agent operator, I want to..."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: "A new `aip <command>` that..."
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any workarounds or alternative approaches?
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - CLI
        - API / Service
        - Trust Model
        - Messaging
        - Skill Signing
        - Documentation
        - Other
