title: "[Q&A] "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        ## Ask a Question
        Have a question about AIP? Ask here and the community will help.
  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: "How do I verify another agent's identity using AIP?"
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Any relevant details (your setup, what you've tried, etc.)
      placeholder: "I'm running aip-identity 0.5.2 on Python 3.11..."
  - type: dropdown
    id: topic
    attributes:
      label: Topic
      options:
        - Installation / Setup
        - Identity & DIDs
        - Vouches & Trust
        - Skill Signing
        - Encrypted Messaging
        - API / Integration
        - Other
