#!/usr/bin/env python3
"""
AIP as a Standalone Library — No Framework Required

Use AIP identity directly in any Python application.
One line to get a cryptographic identity for your agent.

Requirements:
    pip install aip-identity

Usage:
    python standalone_identity.py
"""

from aip_identity.integrations.auto import ensure_identity

# === One line: get or create your agent's identity ===
client = ensure_identity("my-custom-agent", platform="python")
print(f"Agent DID: {client.did}")
print(f"Public key: {client.public_key}")

# === Sign data to prove authorship ===
data = b"This report was generated by my agent on 2025-03-10."
signature = client.sign(data)
print(f"\nSigned data: {signature.hex()[:40]}...")

# === Verify a signature ===
import base64
from nacl.signing import VerifyKey

verify_key = VerifyKey(base64.b64decode(client.public_key))
verify_key.verify(data, signature)
print("✓ Signature verified — data is authentic")

# === Look up another agent ===
try:
    info = client.lookup(client.did)  # Look up ourselves as a test
    print(f"\nAgent info: {info}")
except Exception as e:
    print(f"\nLookup: {e}")

# === Check trust ===
try:
    trust = client.get_trust(client.did)
    print(f"Trust info: {trust}")
except Exception as e:
    print(f"Trust: {e}")

print(f"""
=== What You Can Do ===

client.sign(data)              — Sign bytes with your private key
client.verify(did)             — Challenge-response verification of another agent
client.lookup(did)             — Get registration info for a DID
client.get_trust(did)          — Get trust scores and vouches
client.is_trusted(did)         — Quick boolean trust check
client.vouch(did, scope)       — Vouch for another agent
client.send_message(did, msg)  — Send encrypted message (SealedBox)
client.get_messages()          — Read your encrypted messages
client.get_profile(did)        — Get agent's public profile
client.get_trust_path(a, b)    — Find trust chain between agents
client.save(path)              — Save credentials to file
""")
